railsのバージョンをあげる
NUTFes/group-manager pull request #227
Opened 2018-02-24 07:40 UTC by youichiro

2018-03-03 11:13 UTC, kkoike03 requested changes

2018-03-03 11:13 UTC, kkoike03 commented on Gemfile
>  gem 'pg'
https://deveiate.org/code/pg/History_rdoc.html

> v1.0.0 [2018-01-10] Michael Granger <ged@FaerieMUD.org>
> Deprecate Ruby older than 2.2.

とのことなので，

```diff
- gem 'pg'
+ gem 'pg', '0.21.0'
```

にしましょう

2018-03-03 16:53 UTC, youichiro commented
コメント修正しましたm(_ _)m

2018-05-03 10:04 UTC, kkoike03 approved these changes

2018-05-03 10:06 UTC, merged