「ステージ利用の申請」の日付を年度ごと自動で切り替えるように
NUTFes/group-manager pull request #258
Opened 2018-05-04 11:25 UTC by oba18

resolve #191

2018-05-04 17:02 UTC, youichiro requested changes

2018-05-04 17:02 UTC, youichiro commented on app/models/group.rb
> +    return unless group_category_id == 3
コメントが削除されていますが、わかりやすいようにコメントは残しておきましょう

2018-05-04 17:02 UTC, youichiro commented on app/models/group.rb
> +    date1 = FesDate.where(fes_year_id: FesYear.this_year).where(days_num: 1).first.id
```ruby
FesDate.where(fes_year_id: FesYear.this_year, days_num: 1).first.id
```

と書いた方がスマートかな

2018-05-04 17:02 UTC, youichiro commented on app/models/group.rb
> +    date1 = FesDate.where(fes_year_id: FesYear.this_year).where(days_num: 1).first.id
変数名はなるべく役割が明確にわかる名前が良いです
`this_year_first_date`, `this_year_second_date`とかどうでしょうか

2018-05-04 17:14 UTC, youichiro commented
`bundle exec rake db:seed_fu`の実行が必要なことを記載しておきましょう。

2018-05-05 13:32 UTC, oba18 commented on app/models/group.rb
> +    date1 = FesDate.where(fes_year_id: FesYear.this_year).where(days_num: 1).first.id
了解です！

2018-05-05 13:32 UTC, oba18 commented on app/models/group.rb
> +    date1 = FesDate.where(fes_year_id: FesYear.this_year).where(days_num: 1).first.id
そうします！ありがとうございます！

2018-05-06 14:48 UTC, youichiro approved these changes

2018-05-12 05:25 UTC, merged