申請期限をアプリ上で総務の人が変更できるように
NUTFes/group-manager pull request #342
Opened 2019-04-30 06:08 UTC by oba18

resolve #332 

## やったこと
1. `group_manager_common_option`モデルに`order_deadline`カラムを追加
2. `app/admin/group_manager_common_option.rb`でindexにカラムを追加，同時に`manager`権限では編集も可能に
3. `config/locales.01_model/ja.yml`で日本語を「申請締め切り」に
4. `app/controller/welcom_controller.rb`で申請締め切りを呼び出す変数を用意
5. `app/view/welcome/_dashboard.html`で呼び出し
6. 少し文字を強調

## これから総務の人がやること
管理画面の(アプリ共通設定)から"編集"をクリックして申請の締め切り日を入力，その後更新

## 備考
`manager`権限だと(アプリ共通設定)は作成と削除が不可能ではあるが編集は可能の設定になっていた

2019-05-01 06:57 UTC, youichiro requested changes

2019-05-01 06:57 UTC, youichiro commented on db/migrate/20190429091222_add_order_deadline_to_group_manager_common_options.rb
> +alass AddOrderDeadlineToGroupManagerCommonOptions < ActiveRecord::Migration[5.2]
`class`のtypo

2019-05-01 06:57 UTC, youichiro commented on app/controllers/welcome_controller.rb
> +    @date_of_order_deadline = GroupManagerCommonOption.first.order_deadline
何も文字列が設定されていない場合は，デフォルト値（\<DEADLINE\>みたいな）表示するようにして，未設定なのがぱっと見でわかるとミスが減りそう

2019-05-01 11:37 UTC, youichiro requested changes

2019-05-01 11:37 UTC, youichiro commented on app/controllers/welcome_controller.rb
> +    end
`@date_of_order_deadline = GroupManagerCommonOption.first.order_deadline.presence || "<DEADLINE>"` て書くとスマートそう

2019-05-01 11:38 UTC, youichiro commented on app/controllers/welcome_controller.rb
> +    end
https://qiita.com/quattro_4/items/88578a2044c423cab3f0

2019-05-01 11:49 UTC, youichiro approved these changes

2019-05-01 11:49 UTC, youichiro commented
LGTM

2019-05-08 07:04 UTC, kichikawa approved these changes

2019-05-08 09:34 UTC, merged