パーテーション足を申請可能に&パーテーション足が未申請のときWarning
NUTFes/group-manager pull request #346
Opened 2019-05-10 18:55 UTC by youichiro

resolve #345

2019-05-11 15:06 UTC, oba18 approved these changes

2019-05-11 15:07 UTC, kichikawa requested changes
コンフリクト起きちゃってるのとコメント修正
あとは足のみ申請が通っちゃうね

2019-05-11 15:07 UTC, kichikawa commented on db/fixtures/rental_item_allow_list.rb
> +  { id: 46, rental_item_id: 11, group_category_id: 2}, # 模擬店(食品)
細かいけどコメント間違ってるよー

2019-05-11 15:13 UTC, youichiro commented on db/fixtures/rental_item_allow_list.rb
> +  { id: 46, rental_item_id: 11, group_category_id: 2}, # 模擬店(食品)
m(_ _)m

2019-05-11 16:57 UTC, youichiro commented
> あとは足のみ申請が通っちゃうね
足のみの申請もwarning出すようにします

加えて，パーテーションの数と足の数の組み合わせに不適切な場合にもwarningを出すようにします
```
パーテーションの数：パーテーション足の数の適切な組み合わせ
1枚→2本
2枚→3本，4本
3枚→4本，5本，6本
4枚→5本，6本，7本，8本
5枚→6本，7本，8本，9本，10本
...
```

2019-05-12 15:20 UTC, kichikawa approved these changes

2019-05-12 17:26 UTC, merged

2019-05-13 14:58 UTC, youichiro commented
このプルリクではパーテーション足をステージ団体にも申請可能にしたが，https://github.com/NUTFes/group-manager/pull/353 で申請不可に変更した．