setup.mdにHerokuの情報を消して，VPSの情報を記載する
NUTFes/group-manager pull request #387
Opened 2020-02-11 09:15 UTC by oba18

# 内容
Herokuが現在使われていないので，VPSでのデプロイの方法や，現在の状況等を`docs/setup.md`に記載した．

# 参考
https://github.com/NUTFes/group-manager/pull/334

2020-02-16 05:37 UTC, youichiro requested changes
ここだけ修正お願いします。

2020-02-16 05:37 UTC, youichiro commented on docs/setup.md
> +-nginxの設定ファイル: `/etc/nginx/sites-available/group-manager.nutfes.net`
`-nginx` → `- nginx`

2020-02-18 12:39 UTC, oba18 commented
直しました

2020-02-24 08:30 UTC, youichiro approved these changes

2020-02-24 08:30 UTC, merged